# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 14, 22, 10, 13, 513955, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
